---
name: Deploy to Prod
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to deploy'
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: create k8 service
        run: |
          kubectl apply -f ./deploy/service.yml

      - name: create k8 deployment
        run: |
          kubectl apply -f ./deploy/deployment.yml

