---
name: integration-tests
on:
  pull_request:
    
jobs:
  int-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install deps
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: compile
        run: ./mvnw clean compile

      - name: integration test
        run: ./mvnw verify