---
name: package-artifact
on:
  pull_request:

jobs:
  package-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install deps
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: compile
        run: ./mvnw clean compile

      - name: package jar artifact
        run: ./mvnw -Dmaven.test.skip=true package