---
name: unit-tests
on:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install deps
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: compile
        run: ./mvnw clean compile

      - name: unit test
        run: ./mvnw test